---
- name: Permitir sudo sem senha para usuário ufc
  hosts: ativos
  become: yes
  become_method: sudo
  gather_facts: no

  tasks:
    - name: Criar arquivo sudoers para ufc sem senha
      lineinfile:
        path: /etc/sudoers.d/ufc_nopasswd
        line: 'ufc ALL=(ALL) NOPASSWD:ALL'
        create: yes
        mode: '0440'
        validate: 'visudo -cf %s'